@startuml

skinparam usecase {

    BackgroundColor DarkSeaGreen
    BorderColor DarkSlateGray

    BackgroundColor<< MySQL >> YellowGreen
    BorderColor<< MySQL >> YellowGreen

    ArrowColor Olive
    ActorBorderColor black
    ActorFontName Courier

    ActorBackgroundColor<< Human >> Gold
}
Usuario as usr
database "MariaDB" {
[BANCO DE DADOS] as [MySQL]
}
:usr: -left-> [DISCORD BOT] : (1) Insere comando
[DISCORD BOT] -up-> [EDITOR] : (2) Envia a requisicao para o editor
[EDITOR] -up-> [DISCORD BOT] : (3) Retorna o link para o bot
[DISCORD BOT] -up-> [usr] : (4) O bot retorna o link para o usuario

:usr: -left-> [BLOCKLY] : (5) Com o link, o usuario acessa o blockly
[BLOCKLY] -right-> [EDITOR] : (6) As alteracoes feitas pelo usuario sao enviadas ao editor
[EDITOR] -up-> [MySQL] : (7) O servico persiste a informacao no banco de dados MariaDB 
@enduml